packages:
  - apps/**
  - packages/**
  - libs/**
  # Exclude Prisma generated client directories
  - '!**/prisma/**/client'
  - '!**/src/prisma/**/client'

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - protobufjs
  - unrs-resolver
