packages:
  - apps/**
  - packages/**
  - libs/**
  # Exclude Prisma generated client directories
  - '!**/prisma/**/client'
  - '!**/src/prisma/**/client'

allowBuilds:
  '@mui/x-telemetry': true
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true
  puppeteer: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - protobufjs
  - unrs-resolver
