export const httpHeaders = {
  traceId: 'x-trace-id',
  gatewayJwt: 'x-gateway-jwt',
  timestamp: 'x-timestamp',
  sign: 'x-sign',
  appSource: 'x-app-source',
  env: 'x-env',
  accessToken: 'access-token',
  appLocale: 'x-locale',
  acceptLanguage: 'accept-language',
  contentType: 'content-type',
  authorization: 'authorization',
  cookie: 'cookie',
  setCookie: 'set-cookie',
} as const;
