http:
  env: dev
  port: 8080
  prefix: api
  timeout: 5000
  retryCount: 3
  retryDelay: 500

swagger:
  title: 管理后台
  version: 1.0
  prefix: api-docs
  description: 管理后台接口文档

auth:
  jwtSecret: ${JWT_SECRET}

DBConnections:
  - enable: true
    options:
      name: CORE_SERVICE_DB
      uri: ${CORE_SERVICE_DB}

microServices:
  - name: core-service
    enable: true
    options:
      host: ${CORE_SERVICE_HOST}
      port: 8081
      gatewayPrefix: /api/core
      pathRewrite: /core-service
  - name: core-service-api
    enable: true
    options:
      host: ${CORE_SERVICE_HOST}
      port: 8081
      gatewayPrefix: /api/core-service
      pathRewrite: /core-service
  - name: auth-service
    enable: true
    options:
      host: ${AUTH_SERVICE_HOST}
      port: 8082
      gatewayPrefix: /api/auth
      pathRewrite: /auth-service
  - name: document-service
    enable: true
    options:
      host: ${DOCUMENT_SERVICE_HOST}
      port: 8083
      gatewayPrefix: /api/document
      pathRewrite: /document-service

cors:
  allowedHeaders:
    - X-timestamp
    - Access-Token
    - Accept
    - Content-Type
    - X-Sign
    - x-locale
    - Locale
  origin:
    - http://localhost:3001
  credentials: true
  optionsSuccessStatus: 204
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
